package:
  name: demo1
  version: "1.0.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/mahitha-raj/demo1.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - configparser
    - flask-wtf
    - gunicorn
    - matplotlib
    - pandas
    - pyarrow
    - scipy
    - seaborn

test:
  imports:
    - demo1

about:
  home: https://github.com/mahitha-raj/demo1
  license: MIT
  license_file: LICENSE